2019-02-24 08:46:10,153 ERROR: Exception on /auth/login [GET] [in /home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/app/auth/routes.py", line 29, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2019-03-02 08:43:19,330 INFO: Microblog startup [in /home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/app/__init__.py:75]
2019-03-03 21:46:38,986 INFO: Microblog startup [in /home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/app/__init__.py:75]
2019-03-03 21:49:08,989 INFO: Microblog startup [in /home/tri/stack-camp/pre-course-prep-weeks-1-3/Flask-master-tutorial/The-Flask-Mega-Tutorial/app/__init__.py:75]
